### ISSUE TITLE
Unable to find any public page NPM latest

### ISSUE THREAD

**Issue by darius00klokj** [asnunes/notion-page-to-html#24] opened 2022-02-21 10:47 UTC
`NotionPageToHtml.convert("https://www.notion.so/asnunes/Simple-Page-Text-2-4d64bbc0634d4758befa85c5a3a6c22f").then((page) => console.log(page));`

**Error: Can not find Notion Page of id 4d64bbc0-634d-4758-befa-85c5a3a6c22f. Is the url correct? It is the original page or a redirect page (not supported)?**

My setup:
npm version 8.3.1
node v16.14.0 

Same error on:
https://npm.runkit.com/notion-page-to-html

**Comment by MemerGamer** [comment] 2022-06-23 13:25
Same issue here

**Comment by asnunes** [comment] 2022-07-30 16:34
I was not able to reproduce it either locally or on the given link for the current release. Closing it by now

**Closed by asnunes** 2022-07-30 16:34 UTC
